name = "parliament-bills"
compatibility_date = "2026-02-26"
pages_build_output_dir = ".output/public"

[[d1_databases]]
binding = "DB"
database_name = "parliament-bills"
database_id = "replace-with-d1-database-id"
migrations_dir = "migrations"
